#!/bin/bash

title=$1
clean_title=`echo "$title" | sed 's|[ )(]|_|g'`

LIFEDIR=/notes/life
year=$(date +%Y)
month_short=$(date +%b)
month_num=$(date +%m)
day=$(date +%d)

currdir=$LIFEDIR/${year}/${month_num}-${month_short}

mkdir -p $currdir
cd $currdir

# Find number of days since my birthday
day_no=$(python3 -c "\
import datetime;\
birthday = datetime.date(1996, 4, 2);\
today = datetime.date.today();\
day_no = (today - birthday).days + 1;\
print('{:05}'.format(day_no));\
")

# Now create file for today
fname_start="Day_${day_no}"

for f in ${fname_start}*; do
    # Check if a journal entry has been made today
    if [ -f "$f" ]; then 
        # If it has, open it directly
        nvim "$f"
    else
        # If No entry has been made today then
        # create a new entry
        # TODO: If title is empty, ask for a title here
        fname="${fname_start}_${clean_title}.md"

        cat << EOF > $fname
        ---
        title: "Day ${day_no} - ${title}"
        date: $(date +"%Y-%m-%dT%H:%M:%S")
        ---

        EOF

        nvim "$fname"
    fi
    break
done

