#!/bin/bash

CABINET=~/Dropbox/cabinet
JOURNAL=$CABINET/journal
NOTES=$JOURNAL/notes
LOGS=$JOURNAL/logs

## Journal
oxdiary () {
    $EDITOR $JOURNAL/diary/$(date +%F).md
}

oxdream () {
    $EDITOR $JOURNAL/dream/$(date +%F).md
}

oxantisocial () {
    $EDITOR $JOURNAL/antisocial/$(date +%FT%H:%M:%S).md
}

oxwork () {
    # work journal
    $EDITOR $JOURNAL/work/$(date +%Y).md
}

oxfood () {
    $EDITOR $LOGS/food/$(date +%Y).md
}

oxfind () {
    # searches for a term, shows a list of all files with that term
    # shows a preview of each file
    cd $JOURNAL
    local query=${@-""}
    $EDITOR "$(ag -G '(md|txt)$' -l $query | fzf --preview='pygmentize {}' --color light --margin 5,20)"
}

oxsearch () {
    ag -C 3 -G '(md|txt)$' "$@" $JOURNAL
}

oxtags () {
    # searches for ALL tags like #yolo #wow #ethan #great #moves #such doge
    # Specific tag search can simply be done by oxsearch()
    if [ -z "$@" ]; then
        ag -G '(md|txt)$' '#[a-zA-Z\-_0-9!]+' $JOURNAL
    else
        ag -G '(md|txt)$' "#$@" $JOURNAL
    fi
}

oxmentions () {
    # searches for mentions like @ox @rogue @noob @2016-02-16
    ag -G '(md|txt)$' '@[a-zA-Z\-_0-9!]+' $JOURNAL
}

oxtodos () {
    ag -G '(md|txt)$' 'TODO' $JOURNAL
}

oxedit () {
    cd $JOURNAL
    local query=${@-""}
    $EDITOR "$(fzf --preview='head -$LINES {}' -1 -q "$query")"
}

ncreate () {
    local query=${@-""}
    local p=$(find -L $NOTES -type d ! -path \*.git\* | sed "s|.*notes||" | fzf -1 -q "$@")
    cd $NOTES/$p
    $EDITOR
}

# Create snippet
nsnip() {
    # pbpaste and pbcopy should be mapped to xlcip on linux in zshrc
    local genname=`pbpaste | head -c 25 | sed 's|\ |_|g' | sed 's|/|_|g' `
    local filename=${@:-$genname}
    local slug=`echo $filename | sed 's|\ |_|g' | sed 's|[_]*$||'`
    pbpaste >>! $NOTES/snips/$(date +%F)-${slug}.md
    echo "\n" >>! $NOTES/snips/$(date +%F)-${slug}.md
}

# Inbox to dump everything which will later be organized
alias oxin="$EDITOR $JOURNAL/inbox.md"
alias -g inbox="$JOURNAL/inbox.md"

# Quick jumps
alias nt='cd $NOTES'
alias jr='cd $JOURNAL'
