" vim:fdm=marker
" oxalorgs vimrc
"{{{ 
" Latest version: https://github.com/oxalorg/dotfiles
" * Customized for personal use.
" * Minimal with a very low footprint.
"}}}
set nocompatible  " Be iMproved
let mapleader = "\<Space>"
filetype plugin indent on
syntax enable

let s:uname = system("uname")
if s:uname == "Darwin\n"
else
endif


"" Custom
"{{{
autocmd CompleteDone * pclose
inoremap qp <Esc> " map ESC to something senible
noremap : ;
noremap ; :
cmap w!! w !sudo tee % >/dev/null           " save with sudo
colo ronox
"}}}

"" Functions
"{{{
command -nargs=1 E execute('silent! !mkdir -p "$(dirname "<args>")"') <Bar> e <args>
"}}}


" Leader
"{{{
nnoremap <silent> <Leader>ev :e $MYVIMRC<CR>    " edit vimrc
nnoremap <silent> <Leader>ez :e ~/.zshrc<CR>    " edit zshrc
nnoremap <silent> <Leader>sv :so $MYVIMRC<CR>   " source vimrc
nnoremap <silent> <Leader>dd :bd<CR>
"}}}


"{{{ Integrating 'fzy'
function! FzyCommand(choice_command, vim_command)
try
    let output = system(a:choice_command . " | fzy ")
catch /Vim:Interrupt/
    " Swallow errors from ^C, allow redraw! below
endtry
redraw!
if v:shell_error == 0 && !empty(output)
    "exec a:vim_command . ' ' . output
    exec a:vim_command . ' ' . escape(output, ' ')
endif
endfunction

nnoremap <leader>oo :call FzyCommand("ag . -l -g ''", ":e")<cr>
nnoremap <leader>ov :call FzyCommand("ag . -l -g ''", ":vs")<cr>
nnoremap <leader>os :call FzyCommand("ag . -l -g ''", ":sp")<cr>
"}}}

"" Notes
"{{{
nnoremap <leader>ns :call FzyCommand("ag ~/Dropbox/cabinet/notes -l -g ''", ":e")<cr>
"nnoremap <leader>ns :call FzyCommand("ag ~/Dropbox/cabinet/notes -l -g ''", ":e")<cr>
"}}}

"" Journal
"{{{
" Logs
fun! OpenLog()
    let fname = strftime("%Y-%m-%d")
    exe ":e ~/Dropbox/cabinet/journal/logs/daily/" . fname . ".txt"
endfun
nnoremap <silent> <leader>jl :call OpenLog()<CR>

" Todos
fun! OpenTodo()
    let fname = strftime("%Y/%m")
    exe ":E ~/Dropbox/cabinet/journal/todos/" . fname . ".txt"
endfun

nnoremap <silent> <leader>jt :call OpenTodo() <CR>


"}}}


"" Movement
"{{{
" Move a line of text using ALT+[jk] or Comamnd+[jk] on mac
nmap <M-j> mz:m+<cr>`z
nmap <M-k> mz:m-2<cr>`z
vmap <M-j> :m'>+<cr>`<my`>mzgv`yo`z
vmap <M-k> :m'<-2<cr>`>my`<mzgv`yo`z
nnoremap <up> <nop>     " No arrows keys
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
nnoremap j gj
nnoremap k gk
"}}}


"" Sane defaults
"{{{
set backspace=indent,eol,start  "Allow backspace in insert mode
set history=1000                "Store lots of :cmdline history
set undolevels=1000             " use many muchos levels of undo
set wildmode=list:longest
set wildmenu                    "enable ctrl-n and ctrl-p to scroll thru matches
set wildignore=*.o,*.obj,*~     "stuff to ignore when tab completing
set wildignore+=*.swp,*.bak,*.pyc,*.class
set wildignore+=*DS_Store*
set wildignore+=*.png,*.jpg,*.gif
set title                       " change the terminal's title
set visualbell                  " don't beep
set noerrorbells                " don't beep
set path+=**                    " Search down into subfolders
set autoread                    " Reload files changed outside vim
set hidden                      " Allows dirty buffers to be hidden
set timeoutlen=1000 ttimeoutlen=0
set mouse=a
"}}}


"" Spacing and Indent
"{{{
set tabstop=4  		" number of visual spaces interpreted for each tab
set softtabstop=4   " number of spaces inserted when using tab
set expandtab       " expand tabs to spaces
set shiftwidth=4    " When indenting with > / <
set autoindent
set smartindent
nnoremap p p=`]<C-o> " Auto indent pasted text
nnoremap P P=`]<C-o>
"}}}


"" UI
"{{{
set relativenumber number
set wildmenu            " Display all matching files when we tab complete
set showcmd             " Display commands at bottom corner
set lazyredraw          " redraw only when we need to.
set showmatch           " highlight matching [{()}]
" show tabs, and trailing spaces
set listchars=tab:>~,nbsp:_,trail:.
set list
"}}}


"" Scrolling 
"{{{
set scrolloff=8         "Start scrolling when we're 8 lines away from margins
set sidescrolloff=15
set sidescroll=1
"}}}


"" Searching
"{{{
set ignorecase
set smartcase
set incsearch
set nohlsearch
nnoremap <silent> <Leader>/ :nohlsearch<CR>    " clears the hl search
"}}}


"" Folding
"{{{
set foldenable          " enable folding
set foldlevelstart=10   " open most folds by default
set foldnestmax=10      " 10 nested fold max
nnoremap , za           " comma open/closes folds
nnoremap <Tab> za           " comma open/closes folds
set foldmethod=indent   " fold based on indent level
"}}}


"" Status line
"{{{
set laststatus=2    " Always show the status line
"set statusline=\ %{HasPaste()}%F%m%r%h\ %w\ \ CWD:\ %r%{getcwd()}%h\ \ \ Line:\ %l
"}}}


"" Filetype Specifics
"{{{
" Markdown
autocmd BufNewFile,BufReadPost *.md set filetype=markdown
autocmd Filetype markdown call SetMarkdownOptions()
function! SetMarkdownOptions()
set textwidth=64
set formatprg=par\ -w62
set formatoptions+=t
highlight CursorLine ctermbg=NONE
let g:markdown_fenced_languages = ['html', 'python', 'bash=sh']
endfunction

" Makefile
autocmd FileType make setlocal noexpandtab
"}}}


"" Plugins
"{{{
" Load vim-plug
" Change ~/.vim/vim-plugins file to edit plugins
source ~/.vim/vim-plugins

" Vimwiki
let g:vimwiki_list = [{'path': '~/Dropbox/cabinet/wiki/',
                   \ 'syntax': 'markdown', 'ext': '.md'}]
"}}}


"" Experimental
"{{{
" Testing out these settings
" Better defaults
let g:netrw_banner=0        " disable annoying banner
let g:netrw_browse_split=4  " open in prior window
let g:netrw_altv=1          " open splits to the right
let g:netrw_liststyle=3     " tree view
let g:netrw_list_hide=netrw_gitignore#Hide()
let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\+'

" Smooth Scrolling
function! SmoothScroll(up)
if a:up
    let scrollaction=""
else
    let scrollaction=""
endif
exec "normal " . scrollaction
redraw
let counter=1
while counter<&scroll
    let counter+=1
    sleep 5m
    redraw
    exec "normal " . scrollaction
endwhile
endfunction

nnoremap <C-U> :call SmoothScroll(1)<Enter>
nnoremap <C-D> :call SmoothScroll(0)<Enter>
inoremap <C-U> <Esc>:call SmoothScroll(1)<Enter>i
inoremap <C-D> <Esc>:call SmoothScroll(0)<Enter>i


" ================ Persistent Undo ==================
" Check for conflics with swap files
" Keep undo history across sessions, by storing in file.
" Only works all the time.
if has('persistent_undo') && !isdirectory(expand('~').'/.vim/backups')
silent !mkdir ~/.vim/backups > /dev/null 2>&1
set undodir=~/.vim/backups
set undofile
endif

" ================ Completion =======================

" Auto indent pasted text
nnoremap p p=`]<C-o>
nnoremap P P=`]<C-o>

set nostartofline
set cmdheight=2
set lazyredraw          " redraw only when we need to.
set cursorline          " highlight current line
nnoremap gV `[v`]       " highlight last inserted text

set grepprg=ag\ --nogroup\ --nocolor\ --column

augroup quickfix
autocmd!

autocmd QuickFixCmdPost [^l]* cwindow
autocmd QuickFixCmdPost l*    lwindow
autocmd VimEnter        *     cwindow
augroup END

"To have a space (ASCII 32) considered as a valid character for a file name, add the following to your vimrc:
set isfname+=32


set pastetoggle=<F2>

"}}}


