#!/bin/bash

# TODO: Set these variables IF not defined in zshrc/bashrc
#CABINET=~/Dropbox/cabinet
#NOTES=$CABINET/notes
#JOURNAL=$CABINET/journal

## Journal
oxdiary () {
    $EDITOR $CABINET/journal/diary/$(date +%F).md
}

oxdream () {
    $EDITOR $CABINET/journal/diary/$(date +%F).md
}

oxantisocial () {
    $EDITOR $CABINET/journal/antisocial/$(date +%FT%H:%M).md
}

## Notes
nsearch () {
    cd $NOTES
    local query=$@ || ""
    $EDITOR "$(fzf --preview='head -$LINES {}' -1 -q $query)"
}

ncreate () {
    local query=$@ || ""
    local p=$(find -L $NOTES -type d ! -path \*.git\* | sed "s|.*notes||" | fzf -1 -q "$@")
    cd $NOTES/$p
    $EDITOR
}

# Create snippet
nsnip() {
    # pbpaste and pbcopy should be mapped to xlcip on linux in zshrc
    local content=pbpaste
    local genname=`pbpaste | head -c 25`
    local filename=${@:-$genname}
    local slug=`echo $filename | sed 's|\ |_|g' | sed 's|[_]*$||'`
    $content >> $NOTES/snips/$(date +%F)-${slug}.md
    echo "\n" >> $NOTES/snips/$(date +%F)-${slug}.md
}

# Edit scratch pad note
alias npad='$EDITOR --cmd "cd /notes" /notes/scratch-pad.md'
alias cpad='cat /notes/scratch-pad.md'
alias ppad='/notes/scratch-pad.md'

alias nt='cd $NOTES'
