#!/bash/bin

## Screenshots
ROGUE_ARK_DIR=/var/www/rogue.oxal.org/public
ROGUE_LOCAL_DIR=$CABINET/www/rogue.oxal.org/public
rougescreen () {
    FILENAME=${1-$(date +%s)}
    URL="http://rogue.oxal.org/img/s/"$FILENAME.png
    #FILENAME=$HOME/Pictures/Screenshots/$FILENAME.png
    FILENAME=$ROGUE_LOCAL_DIR/img/s/$FILENAME.png
    gnome-screenshot $1 -f $FILENAME
    scp $FILENAME ark:$ROGUE_ARK_DIR/img/s/
    echo $URL | pbcopy
    notify-send "URL copied to clipboard"
}

## Upload snippets
roguesnip () {
    fname=${1-$(date +%s)}
    echo "The file name is $fname"
    FILENAME=$ROGUE_LOCAL_DIR/snip/$fname.txt
    input=$(cat | tee "$FILENAME")
    URL="http://rogue.oxal.org/snip/"$fname.txt
    scp $FILENAME ark:$ROGUE_ARK_DIR/snip/
    echo $URL | pbcopy
    notify-send "URL copied to clipboard"
}
